//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsGlobalAPIEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arabalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arabalar()
        {
            this.Satislar = new HashSet<Satislar>();
        }
    
        public int ArabaID { get; set; }
        public Nullable<int> SubeID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<int> Yil { get; set; }
        public string Yakit { get; set; }
        public string Vites { get; set; }
        public Nullable<int> MotorGucu { get; set; }
        public Nullable<int> MotorHacmi { get; set; }
    
        public virtual SubeAbonelik SubeAbonelik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislar { get; set; }
    }
}
