//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsGlobalAPIEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubeLog
    {
        public int LogID { get; set; }
        public string KullaniciAdi { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Islem { get; set; }
        public string Aciklama { get; set; }
    }
}
