//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsGlobal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int MusteriID { get; set; }
        public int SatisID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int TelNo { get; set; }
        public string EPosta { get; set; }
        public System.DateTime KayitTarihi { get; set; }
    
        public virtual Satislar Satislar { get; set; }
    }
}
