//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsGlobal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Satislar()
        {
            this.Musteriler = new HashSet<Musteriler>();
        }
    
        public int SatisID { get; set; }
        public int UrunID { get; set; }
        public string Yetkili { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Ucret { get; set; }
        public double Vergi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteriler> Musteriler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
