//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsGlobal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubeAdmin
    {
        public int AdminID { get; set; }
        public int SubeID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
    
        public virtual SubeAbonelik SubeAbonelik { get; set; }
    }
}
